version: '2.2'
services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - postgresql
    networks:
      - network1
    volumes:
      - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/conf/mysite.conf:/etc/nginx/sites-enabled/mysite.conf
    ports:
      - "80:80"
    command: /bin/bash -c "nginx"
  postgresql:
    image: postgres
    container_name: postgres
    networks:
    - network1
    volumes:
      - ./dataStore/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
networks:
  network1: